### ISSUE TITLE
HHC02219E Error in function getprotobyname("TCP"): No such file or directory

### ISSUE THREAD

**Issue by efission** [Hercules-Aethra/aethra#13]
I'm getting this error:

	HHC02219E Error in function getprotobyname("TCP"): No such file or directory

I looked into the `getprotobyname` function and it seems that it reads protocols out of a database (usually `/etc/protocols`, but not necessarily). From what I've seen, the protocol _names_ – the first field in a record in `protocols` – are lowercase ("`tcp`"), but there are often additional aliases defined in upper or mixed case ("`TCP`"). Some systems (eg Alpine, which uses musl libc) don't define any aliases, so:

	getprotobyname("tcp"); // works
	getprotobyname("TCP"); // fails

Pretty easy fix, something like:

	--- hscutl.c.old
	+++ hscutl.c
	@@ -789,10 +789,10 @@
	     struct protoent * tcpproto;

	     /* Retrieve TCP protocol value (mostly for FreeBSD portability) */
	-    tcpproto = getprotobyname("TCP");
	+    tcpproto = getprotobyname("tcp");
	     if (!tcpproto)
	     {
	-        WRMSG( HHC02219, "E", "getprotobyname(\"TCP\")", strerror( HSO_errno ));
	+        WRMSG( HHC02219, "E", "getprotobyname(\"tcp\")", strerror( HSO_errno ));
		 return -1;
	     }
	     l_tcp = tcpproto->p_proto;
	@@ -897,10 +897,10 @@
	     socklen_t  optlen = sizeof( optval );

	     /* Retrieve TCP protocol value (mostly for FreeBSD portability) */
	-    tcpproto = getprotobyname("TCP");
	+    tcpproto = getprotobyname("tcp");
	     if (!tcpproto)
	     {
	-        WRMSG( HHC02219, "E", "getprotobyname(\"TCP\")", strerror( HSO_errno ));
	+        WRMSG( HHC02219, "E", "getprotobyname(\"tcp\")", strerror( HSO_errno ));
		 return -1;
	     }
	     l_tcp = tcpproto->p_proto;

afaik, lowercase `tcp` should always work, but I only tested it on macOS, Linux-glibc, and Linux-musl.

This is the little bit of test code I made for it to make it easier to check:

	#include <netdb.h>
	#include <stdio.h>

	int
	main(int argc, char **argv)
	{
		struct protoent *sp;
		const char *name;
		const char *name_default = "TCP";

		name = name_default;
		if (argc > 1) name = argv[1];

		setprotoent(0);
		sp = getprotobyname(name);
		if (sp)
			printf("getprotobyname(%s) returned: %s (%d)\n",
					name, sp->p_name, sp->p_proto);
		else
			fprintf(stderr, "getprotobyname(%s) failed\n",
					name);
		endprotoent();

		return 0;
	}

**Comment by Fish-Git** [comment]
I will try to get that fixed in SDL Hyperion as soon as I can. Jay of course will have to fix it in Aethra.

Thanks, whoever-you-are!

**Comment by jmaynard** [comment]
I'll push a fix shortly. The current code works except on musl-based Linux, so just on the off chance that someone (like, say, Windows) did the reverse of musl and only put the upper case version in the database, I'll check for both.

**Comment by Fish-Git** [comment]
> [jmaynard](https://github.com/jmaynard) pushed a commit that referenced this issue [5 minutes ago](https://github.com/Hercules-Aethra/aethra/issues/13#ref-commit-0b33c07)

Wow you're fast! &nbsp; `:)`

**Comment by jmaynard** [comment]
Well, after encouraging him to file the issue on Github, it would serve us all poorly if I didn't push the simple fix...
