### ISSUE TITLE
hostopts detection for non-glibc Linux distros

### ISSUE THREAD

**Issue by efission** [Hercules-Aethra/aethra#15]
When building on Alpine Linux (armv7l), I get warnings like:

    In file included from ccnowarn.h:32,
                     from hstdinc.h:75,
                     from cckdcdsk.c:13:
    ccfixme.h:64:33: note: '#pragma message: hostopts.h(375) : warning : unknown target platform: defaulting to generic platform settings'
       64 |   #define QPRAGMA( x )          _Pragma( #x )
          |                                 ^~~~~~~
    ccfixme.h:102:33: note: in expansion of macro 'QPRAGMA'
      102 |   #define WARNING( _str )       QPRAGMA( message(  WARN_LINE  _str ))
          |                                 ^~~~~~~
    hostopts.h:375:1: note: in expansion of macro 'WARNING'
      375 | WARNING( "unknown target platform: defaulting to generic platform settings" )
          | ^~~~~~~

Currently Linux is detected by checking for `__gnu_linux__`, but this is not defined on my system.

I changed the condition in `hostopts.h` to look for `__linux__` also and the build succeeded.

    $ cat hostopts-linux-generic.patch
    --- hostopts.h.orig
    +++ hostopts.h
    @@ -314,7 +314,7 @@
     /*-------------------------------------------------------------------*/
     /* Hard-coded GNU Linux-specific features and options...             */
     /*-------------------------------------------------------------------*/
    -#elif defined(__gnu_linux__)            /* GNU Linux options         */
    +#elif defined(__gnu_linux__) || defined (__linux__) /* Linux options */
    
     #define DLL_IMPORT              extern
     #define DLL_EXPORT

I have attached [alpine-armv7l-gcc-defines.txt](https://github.com/Hercules-Aethra/aethra/files/14031607/alpine-armv7l-gcc-defines.txt), which was generated by `echo | gcc -dM -E -`, in case there is a different `#define` you wish to use. (But `__linux__` seems the most obvious to me.)

**Comment by jmaynard** [comment]
I check for both __gnu_linux__ and __linux__ in the places where it affects what the code does, and report them separately in the version string.
