### ISSUE TITLE
Better --help handling

### ISSUE THREAD

**Issue by jmaynard** [Hercules-Aethra/aethra#2]
The output of specifying the --help operand on the invocation command is less than helpful.

**Comment by wrljet** [comment]
It would be good to have the standard `--version` switch.

**Comment by wrljet** [comment]
For what it's worth, the `--version` stuff is checked in, and other general improvements to the spewing at start-up.

Bill

**Comment by jmaynard** [comment]
Checked in where?

**Comment by wrljet** [comment]
It's in this repo

**Comment by jmaynard** [comment]
Where? I'm not seeing it.

**Comment by wrljet** [comment]
https://github.com/Hercules-Aethra/aethra/commit/9c59141b3263b03250e973f478a938e27acfba80

**Comment by jmaynard** [comment]
Oh! Duh. Closing.

**Comment by wrljet** [comment]
It doesn't really improve `--help` so much though.
Does get rid of all that extra blurb about the threads starting, etc, though.
