### ISSUE TITLE
Allow setting MAINSIZE smaller than 1 MB

### ISSUE THREAD

**Issue by jmaynard** [Hercules-Aethra/aethra#8]
Some System/360 code gets unhappy in a system with 1 MB of main storage. Allow specifying MAINSIZE in smaller increments.

**Comment by wrljet** [comment]
Jay,

The MAINSIZE command supports suffixes such as 'K'.  So you can specify "512K", for example.

With ARCHLVL set to 370, the minimum core size is 64K.

So I think Hercules already does what you want.

Bill

**Comment by jmaynard** [comment]
So it does. Yay! I love being able to close issues without doing anything.

**Comment by wrljet** [comment]
:-)
