### ISSUE TITLE
Broken URL in readme.md

### ISSUE THREAD

**Issue by josederas** [Hercules-Aethra/aethra#9]
The link for more information about Aethra in the main readme.md is broken.  The link in question is:

http://hercules-aethra.github.io/html/

**Comment by Fish-Git** [comment]
Jay (@jmaynard),

It looks like you haven't created the separate GitHub git repository for Aethra's html documentation yet. It's an easy thing to forget, as it's a completely separate git repository from Aethra's main repository.

Once it's created, then each time a commit is made to Aethra's main `html` subdirectory, you need to make the same change (commit) to your "[**gh-pages**](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site)" repository too.

Yes, it's a PITA to have to maintain it separately, but that's just the way GitHub was designed.

**Comment by jmaynard** [comment]
Fixed, finally, for some values of "fixed". Need to go through and clean up stuff, but at least the doc is there. Thanks for the hint, Fish.
